<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_no_handphone</name>
   <tag></tag>
   <elementGuidId>36d72fc2-036c-4377-b0c5-03a6af0b5dc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_phone_number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#user_phone_number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6a087546-f625-4019-8d06-c8f437dd10bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control rounded-4 p-3</value>
      <webElementGuid>ab070489-705d-4476-ad32-89155102343b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>contoh: +628123456789</value>
      <webElementGuid>513d210f-4997-47c4-ac9e-20832f3445e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>87aa35ce-a16f-4413-badc-c73bbcc5a8fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>772325a5-4cbe-4a60-a13b-2ef137783f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>@#$%#@#$#@$@#@#$@#$@4</value>
      <webElementGuid>b1c1c500-8f5a-44dd-8d6c-e9a2e65d118a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user[phone_number]</value>
      <webElementGuid>14b41d56-90db-4018-b564-35c6b438c105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_phone_number</value>
      <webElementGuid>b31c0ab2-d003-4bf0-a2f7-0bfe29fe1dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_phone_number&quot;)</value>
      <webElementGuid>19758da1-81ca-4cb4-9e41-f1aea2fbf2b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_phone_number']</value>
      <webElementGuid>72273157-2e04-49fe-95c8-868b276ff9bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>53a01f1f-c88a-49b2-9d6b-4ad1ed177d00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'contoh: +628123456789' and @type = 'text' and @name = 'user[phone_number]' and @id = 'user_phone_number']</value>
      <webElementGuid>aba1cdcc-4b0a-4e45-b246-0c8bb50f9785</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
